import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <ul className="flex justify-around">
            <li>
              <Link href="/todo" className="text-white hover:text-gray-400">
                <p>Todo</p>
              </Link>
            </li>
            <li>
              <Link href="/api" className="text-white hover:text-gray-400">
                API
              </Link>
            </li>
          </ul>
        </nav>
        <div style={{ margin: "16px", display: "flex", flex: 1 }}>
          {children}
        </div>
      </body>
    </html>
  );
}
